language: julia

julia:
  - 1.3.1

os:
  - linux
  - windows

notifications:
  email: false

codecov: true

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
